version: "3"

output: prefixed

vars:
  TASKFILE: custodian.yaml

tasks:
  install-dependencies:
    desc: Installing dependencies for something
    cmds:
      - sudo add-apt-repository ppa:deadsnakes/ppa
      - sudo apt update && install software-properties-common wget gpg -y
      - sudo apt install python3.8 python3.8-pip python3.8-venv -y
      - curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
      - pip3 install -r requirement.txt

  start-app:
    desc: Start the apppppsss
    cmds:
      - docker compose up -d
      - uvicorn main:app --host 0.0.0.0
  install-all:
    desc: Run lah
    cmds:
      - task: install-dependencies
      - task: start-app