version: "3"

output: prefixed

vars:
  TASKFILE: custodian.yaml

tasks:
  install-dependencies:
    desc: Installing dependencies for something
    cmds:
      - sudo add-apt-repository ppa:deadsnakes/ppa --yes
      - sudo apt update && sudo apt install software-properties-common wget gpg -y
      - sudo apt install python3.8 python3-pip python3-venv -y
  install-docker:
    desc: Installing docker
      - curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
      - pip3 install -r requirement.txt
  setup-event-util:
    desc: copy and do something
    cmds:
      - task: config-ssh-pass
  config-ssh-pass:
    desc: enable ssh pass
    cmds:
      - sudo sed -i 's/^PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
      - sudo service sshd reload
  start-app-server:
    desc: Start the apppppsss
    cmds:
      - sudo docker compose up -d
      - sh startup.sh
  start-client-watcher:
    desc: Start client watcher
    cmds:
      - sh watcher.sh
  install-all:
    desc: Run lah
    cmds:
      - task: install-dependencies
      - task: install-docker
      - task: start-app-server
      - task: setup-event-util